## Como usar: 
# Considerando Docker Compose V2 e S.O. Linux
#
# docker compose -f docker-compose.yml up --build -d
# docker compose logs -f
# docker exec -it website /bin/bash
# docker compose down

## Copias entre container/local
# docker cp website:/home/node/app/index.html .
# docker cp index.html website:/home/node/app/

## Docker full clean
# docker stop $(docker ps -qa)
# docker rm -f $(docker ps -qa)
# docker rmi -f $(docker images -qa)
# docker volume rm -f $(docker volume ls -q)
# docker network rm $(docker network ls -q)

version: '3.9'

services:
  ###################################
  # Application
  ################################### 
  app-website:
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    image: erivando/website-node:latest
    container_name: website
    restart: always
    user: "root:node"
    ports:
      - "8083:80"
    networks:
      - developer

volumes:
  postgresql_data:
    driver: local
    
networks:
 developer:
   name: developer
   driver: bridge